apiVersion: v1
kind: Pod
metadata:
  name: static-web-test-local-test
  labels:
    role: myrole
spec:
  containers:
    - name: web-1
      image: nginx
      ports:
        - name: web-1
          containerPort: 80
          protocol: TCP
